version: 0.2
phases:
  pre_build:
    commands:
       - docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) 054011781552.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - docker build -t custodianapp . 
      - docker tag custodianapp:latest 054011781552.dkr.ecr.us-west-2.amazonaws.com/custodianapp 
      - docker push 054011781552.dkr.ecr.us-west-2.amazonaws.com/custodianapp
 #security
